apiVersion: batch/v1
kind: Job

metadata:
  generateName: mp12-job-premium-
  # region: us-east-1

spec:
  template:
    spec:
      containers:
      - name: mp12-premium-container
        image: yixiao6/mp12_image:0.0.1
        env:
          - name: DATASET
            value: "kmnist"
          - name: TYPE
            value: "cnn"
        resources:
          limits:
            cpu: "0.9"
          requests:
            cpu: "0.9"
      restartPolicy: Never
  backoffLimit: 4
